version: '3'
services:
  users-service:
    build: ./users-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nestjs-microservices_mynetwork

  tutorials-service:
    build: ./tutorials-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nestjs-microservices_mynetwork

  api-gateway:
    build: ./api-gateway
    ports:
      - "3004:3004"
    depends_on:
      - users-service
      - tutorials-service
    networks:
      - nestjs-microservices_mynetwork

  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nestjs-microservices_mynetwork

networks:
  nestjs-microservices_mynetwork:
    driver: bridge
